//! # spirv-bindgen
//! Library to generate Rust bindings for Spir-V shaders.
//!

mod c_struct;
mod debug;
mod descriptors;
mod entry_points;
mod execution_model;
mod model;
mod push_constants;
mod specialization_constants;

use entry_points::EntryPoints;
use prettyplease::unparse;
use proc_macro2::TokenStream;
use push_constants::PushConstant;
use quote::{ToTokens, quote};
use rspirv_reflect::Reflection;
use specialization_constants::SpecializationConstants;

/// A parsed Spir-V document to generate bindings from.
pub struct Spirv {
    /// The shader's specialization constants.
    pub specialization_constants: Option<SpecializationConstants>,

    /// The shader's entry points.
    pub entry_points: EntryPoints,

    /// The shader's push constants.
    pub push_constants: Vec<PushConstant>,
}

impl Spirv {
    /// Load a Spir-V document from it's bytes.
    pub fn try_from_bytes(bytes: &[u8]) -> Self {
        let spirv = Reflection::new_from_spirv(bytes).unwrap();

        let specialization_constants = SpecializationConstants::new(&spirv);
        let entry_points = EntryPoints::new(&spirv);

        let push_constants = spirv
            .0
            .types_global_values
            .iter()
            .filter_map(|instruction| PushConstant::try_from(instruction, &spirv))
            .collect();

        Self {
            specialization_constants,
            entry_points,
            push_constants,
        }
    }

    /// Print the generated bindings as a pretty string.
    pub fn pretty_string(&self) -> String {
        let file = syn::parse2(self.to_token_stream()).unwrap();

        unparse(&file)
    }
}

impl ToTokens for Spirv {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let specialization_constant = &self.specialization_constants;
        let entry_points = &self.entry_points;
        let push_constants = &self.push_constants;

        // TODO doc comment should include version
        let new_tokens = quote! {
            //! Generated by spriv-bindgen
            //!

            #specialization_constant
            #entry_points
            #( #push_constants )*
        };

        tokens.extend(new_tokens);
    }
}
